My first commit
Sachinbisht27/React_App pull request #48
Opened 2022-11-27 16:39 UTC by Abhishek25081999

2022-11-29 17:53 UTC, rohit123-rawat reviewed
@Abhishek25081999  I thing route is not working so can you check it once and raise the pr again .

2022-11-29 17:54 UTC, rohit123-rawat requested changes

2022-11-29 17:54 UTC, rohit123-rawat commented on .idea/misc.xml
> +</project>
why are these change

2022-11-30 04:57 UTC, Abhishek25081999 commented on .idea/misc.xml
> +</project>
Okay I'll work on it today.

2022-11-30 10:54 UTC, Abhishek25081999 commented
@rohit123-rawat  This PR is not completed yet. I think you are early to review it.

2022-12-20 16:50 UTC, closed without merging